### ISSUE TITLE
Astyanax dependencies

### ISSUE THREAD

**Issue by rroopreddy** [Netflix/astyanax#266] opened 2013-04-02 23:46 UTC
I am trying to use Astyanax client in a java project. Created a basic entity-mapper based example with the following dependencies. When I looked at all the transitive dependency jars that are included, they total to 14.5 MB worth listed below. "cassandra-all" seem to contribute half of this size. I was hoping a smaller code size for a client library. Are all these libraries needed for Astyanax to work? Is there an opportunity to trim these down to bare minimum

1) Maven dependencies 

				<dependencies>
				    <dependency>
				        <groupId>com.netflix.astyanax</groupId>
				        <artifactId>astyanax-core</artifactId>
				        <version>1.56.31</version>
				    </dependency>
				    <dependency>
				        <groupId>com.netflix.astyanax</groupId>
				        <artifactId>astyanax-thrift</artifactId>
				        <version>1.56.31</version>
				        <exclusions>
				            <exclusion>
				                <artifactId>cassandra-all</artifactId>
				                <groupId>org.apache.cassandra</groupId>
				            </exclusion>
				            <exclusion>
				                <artifactId>cassandra-thrift</artifactId>
				                <groupId>org.apache.cassandra</groupId>
				            </exclusion>
				        </exclusions>
				    </dependency>
					<dependency>
						<groupId>com.netflix.astyanax</groupId>
						<artifactId>astyanax-cassandra</artifactId>
						<version>1.56.31</version>
						    <exclusions>
					            <exclusion>
					                <artifactId>cassandra-all</artifactId>
					                <groupId>org.apache.cassandra</groupId>
					            </exclusion>
					            <exclusion>
					                <artifactId>cassandra-thrift</artifactId>
					                <groupId>org.apache.cassandra</groupId>
					            </exclusion>
					        </exclusions>
					</dependency>
					<dependency>
						<groupId>com.netflix.astyanax</groupId>
						<artifactId>astyanax-entity-mapper</artifactId>
						<version>1.56.31</version>
						    <exclusions>
					            <exclusion>
					                <artifactId>cassandra-all</artifactId>
					                <groupId>org.apache.cassandra</groupId>
					            </exclusion>
					            <exclusion>
					                <artifactId>cassandra-thrift</artifactId>
					                <groupId>org.apache.cassandra</groupId>
					            </exclusion>
					        </exclusions>
					</dependency>
				    <dependency>
				        <groupId>org.apache.cassandra</groupId>
				        <artifactId>cassandra-all</artifactId>
				        <version>1.2.1</version>
				    </dependency>
				    <dependency>
				        <groupId>org.apache.cassandra</groupId>
				        <artifactId>cassandra-thrift</artifactId>
				        <version>1.2.1</version>
				    </dependency>
				  </dependencies>

2) Pulls the following JARS for above dependencies (14.5MB)

[INFO] +- com.netflix.astyanax:astyanax-core:jar:1.56.31:compile
[INFO] |  +- com.eaio.uuid:uuid:jar:3.2:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.5:compile
[INFO] |  +- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.3:compile
[INFO] |  +- joda-time:joda-time:jar:1.6.2:compile
[INFO] |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.2:compile
[INFO] |  +- com.github.stephenc.high-scale-lib:high-scale-lib:jar:1.1.2:compile
[INFO] |  +- org.apache.servicemix.bundles:org.apache.servicemix.bundles.commons-csv:jar:1.0-r706900_3:compile
[INFO] |  +- com.google.guava:guava:jar:11.0.1:compile
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  +- org.xerial.snappy:snappy-java:jar:1.0.4.1:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.4:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.6.4:compile
[INFO] |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.2:compile
[INFO] |  \- org.codehaus.jettison:jettison:jar:1.2:compile
[INFO] |     \- stax:stax-api:jar:1.0.1:compile
[INFO] +- com.netflix.astyanax:astyanax-thrift:jar:1.56.31:compile
[INFO] |  +- com.netflix.astyanax:astyanax-recipes:jar:1.56.31:compile
[INFO] |  \- org.apache.thrift:libthrift:jar:0.7.0:compile
[INFO] |     +- javax.servlet:servlet-api:jar:2.5:compile
[INFO] |     \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |        +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |        \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] +- com.netflix.astyanax:astyanax-cassandra:jar:1.56.31:compile
[INFO] |  \- org.jboss.netty:netty:jar:3.2.4.Final:compile
[INFO] +- com.netflix.astyanax:astyanax-entity-mapper:jar:1.56.31:compile
[INFO] |  \- javax.persistence:persistence-api:jar:1.0:compile
[INFO] +- org.apache.cassandra:cassandra-all:jar:1.2.1:compile
[INFO] |  +- com.ning:compress-lzf:jar:0.8.4:compile
[INFO] |  +- commons-cli:commons-cli:jar:1.1:compile
[INFO] |  +- org.antlr:antlr:jar:3.2:compile
[INFO] |  |  \- org.antlr:antlr-runtime:jar:3.2:compile
[INFO] |  |     \- org.antlr:stringtemplate:jar:3.2:compile
[INFO] |  |        \- antlr:antlr:jar:2.7.7:compile
[INFO] |  +- org.apache.cassandra.deps:avro:jar:1.4.0-cassandra-1:compile
[INFO] |  |  \- org.mortbay.jetty:jetty:jar:6.1.22:compile
[INFO] |  |     +- org.mortbay.jetty:jetty-util:jar:6.1.22:compile
[INFO] |  |     \- org.mortbay.jetty:servlet-api:jar:2.5-20081211:compile
[INFO] |  +- jline:jline:jar:1.0:compile
[INFO] |  +- com.googlecode.json-simple:json-simple:jar:1.1:compile
[INFO] |  +- org.yaml:snakeyaml:jar:1.6:compile
[INFO] |  +- edu.stanford.ppl:snaptree:jar:0.1:compile
[INFO] |  +- com.yammer.metrics:metrics-core:jar:2.0.3:compile
[INFO] |  +- log4j:log4j:jar:1.2.16:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.2:runtime
[INFO] |  \- com.github.stephenc:jamm:jar:0.2.5:compile
[INFO] +- org.apache.cassandra:cassandra-thrift:jar:1.2.1:compile

**Comment by ckalantzis** [comment] 2015-05-05 16:59
duplicate of #46

**Closed by ckalantzis** 2015-05-05 16:59 UTC
